title: Your awesome title
author: rxpha
email: rapha.diogenes@gmail.com
theme: minima
description: I'm really enjoying take that course, I started from 0 and now I've learned a bunch of useful things. 
I'm learning from my work but I don't need this to work, it's only because I have free-time and my closest co-worker is such a jerk.
I'm fresh at the company and I need to pretend I'm working at least.

# this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

# social links
twitter_username: raphaxscxs # DO NOT include the @ character, or else the build will fail!
github_username:  rxpha # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
